### ISSUE TITLE
Improvement for phpBB 3.2 needed

### ISSUE THREAD

**Issue by Crizz0** [kasimi/phpbb-ext-postnumbers#10]
Hi,

you extension uses the MINI_POST_IMG to inject his content in https://github.com/kasimi/phpbb-ext-postnumbers/blob/master/kasimi/postnumbers/event/listener.php#L257 

The variable MINI_POST_IMG is no longer existing in phpBB  3.2: See: https://github.com/phpbb/phpbb/blob/3.2.x/phpBB/styles/prosilver/template/viewtopic_body.html#L287-L289 

So you need at least change this for phpBB 3.2 and manipulate a different variable. 

Regards

**Comment by kasimi** [comment]
Well, this took a while to get fixed and tested but it's now working with phpBB 3.2x. Related commit: 9d7667e. As of [v1.1.0](https://github.com/kasimi/phpbb-ext-postnumbers/releases/v1.1.0) the post number is displayed before the post image, instead of between post image and post author name.

Thanks for bringing it to my attention early enough.

**Comment by Crizz0** [comment]
You are welcome
